<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_message_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sun Jun 26 11:19:24 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPropelGuardMessagesPlugin.lib.model
 */
class sfGuardMessageUserPeer extends BasesfGuardMessageUserPeer {

} // sfGuardMessageUserPeer
