propel:
  _attributes:      { package: plugins.sfGuardMessagesPlugin.lib.model }

  sf_guard_messages_priority:
    _attributes:    { phpName: sfGuardMessagesPriority }
    id:             ~
    name:           { type: varchar, size: 255, required: true, index: unique }
    description:    { type: longvarchar }

  sf_guard_messages_type:
    _attributes:    { phpName: sfGuardMessagesType }
    id:             ~
    name:           { type: varchar, size: 255, required: true, index: unique }
    description:    { type: longvarchar }

  sf_guard_messages_message:
    _attributes:    { phpName: sfGuardMessagesMessage }
    id:             ~
    type_id:        { type: integer, required: true, foreignTable: sf_guard_messages_type, foreignReference: id, onDelete: cascade }
    priority_id:    { type: integer, required: true, foreignTable: sf_guard_messages_priority, foreignReference: id, onDelete: cascade }
    message:        { type: longvarchar, required: true }
    start_date:     { type: date, required: true }
    end_date:       { type: date }

  sf_guard_messages_message_group:
    _attributes:    { phpName: sfGuardMessagesMessageGroup }
    message_id:     { type: integer, required: true, primaryKey: true, foreignTable: sf_guard_messages_message, foreignReference: id, onDelete: cascade }
    group_id:       { type: integer, required: true, primaryKey: true, foreignTable: sf_guard_group, foreignReference: id, onDelete: cascade }

  sf_guard_messages_message_user:
    _attributes:    { phpName: sfGuardMessagesMessageUser }
    message_id:     { type: integer, required: true, primaryKey: true, foreignTable: sf_guard_messages_message, foreignReference: id, onDelete: cascade }
    user_id:        { type: integer, required: true, primaryKey: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
